Add sauce-rest-api test dependency so that SeleniumFactory.create() will succeed in tests instead of throwing a ClassNotFoundError: java.lang.NoClassDefFoundError: com/saucelabs/rest/Credential 	at com.saucelabs.sauce_ondemand.driver.SauceOnDemandSPIImpl.populateParameterMap(SauceOnDemandSPIImpl.java:90) 	at com.saucelabs.sauce_ondemand.driver.SauceOnDemandSPIImpl.createSelenium(SauceOnDemandSPIImpl.java:63) 	at com.saucelabs.selenium.client.factory.SeleniumFactory.createSelenium(SeleniumFactory.java:280) 	at com.saucelabs.selenium.client.factory.SeleniumFactory.createSelenium(SeleniumFactory.java:255) 	at com.saucelabs.selenium.client.factory.SeleniumFactory.create(SeleniumFactory.java:70)